export default {
  extends: ["stylelint-config-standard"],
  ignoreFiles: [
    "node_modules/**",
    "dist/**",
    "dist-ts/**",
    "artifacts/**",
    ".vercel/**",
    ".venv/**",
    "data/**",
    "FantasyIQ/data/**",
    "public/data/**",
    "public/FantasyIQ/data/**",
  ],
  rules: {
    "alpha-value-notation": null,
    "at-rule-empty-line-before": null,
    "color-function-alias-notation": null,
    "color-function-notation": null,
    "color-hex-length": null,
    "custom-property-empty-line-before": null,
    "custom-property-pattern": null,
    "declaration-empty-line-before": null,
    "declaration-property-value-no-unknown": null,
    "hue-degree-notation": null,
    "media-feature-range-notation": null,
    "no-descending-specificity": null,
    "no-duplicate-selectors": null,
    "property-no-deprecated": null,
    "property-no-vendor-prefix": null,
    "selector-class-pattern": null,
    "selector-not-notation": null,
    "value-keyword-case": null,
  },
};
