import { generateWaiverSniper, type WaiverSniperContext } from "./waiverSniper";

export const waiverSniperExampleInput: WaiverSniperContext = {
  scoringSettings: { receptionPoints: 1 },
  startingSlots: { QB: 1, RB: 2, WR: 2, TE: 1, FLEX: 1, DST: 1, K: 1 },
  benchSize: 7,
  totalTeams: 12,
  currentWeek: 5,
  seasonPhase: "regular_season",
  faabBudget: 100,
  remainingFaabBudget: 76,
  leagueCompetitiveness: 0.72,
  waiverSettings: { mode: "FAAB", minimumBid: 1 },
  currentRosterConstruction: [
    { playerId: "qb1", name: "Starter QB", position: "QB", projectedPoints: 18.1, byeWeek: 11, injuryStatus: "ACTIVE" },
    { playerId: "rb1", name: "RB Anchor", position: "RB", projectedPoints: 16.5, restOfSeasonValue: 110, byeWeek: 9, injuryStatus: "ACTIVE" },
    { playerId: "rb2", name: "Fragile RB", position: "RB", projectedPoints: 8.1, restOfSeasonValue: 42, byeWeek: 5, injuryStatus: "ACTIVE", volatility: 7 },
    { playerId: "wr1", name: "WR Anchor", position: "WR", projectedPoints: 17.4, restOfSeasonValue: 118, byeWeek: 8, injuryStatus: "ACTIVE" },
    { playerId: "wr2", name: "WR Starter", position: "WR", projectedPoints: 12.2, restOfSeasonValue: 74, byeWeek: 10, injuryStatus: "ACTIVE" },
    { playerId: "te1", name: "TE Starter", position: "TE", projectedPoints: 8.4, restOfSeasonValue: 48, byeWeek: 7, injuryStatus: "ACTIVE" },
    { playerId: "bench-rb", name: "Low Ceiling RB", position: "RB", projectedPoints: 5.6, restOfSeasonValue: 24, byeWeek: 12, injuryStatus: "ACTIVE" },
    { playerId: "bench-wr", name: "Bench WR", position: "WR", projectedPoints: 7.1, restOfSeasonValue: 32, byeWeek: 6, injuryStatus: "ACTIVE" },
    { playerId: "dst1", name: "DST", position: "DST", projectedPoints: 6.1, byeWeek: 14, injuryStatus: "ACTIVE" },
    { playerId: "k1", name: "Kicker", position: "K", projectedPoints: 7.0, byeWeek: 13, injuryStatus: "ACTIVE" },
  ],
  liveFreeAgents: [
    {
      id: "fa-rb",
      name: "Breakout Handcuff RB",
      position: "RB",
      projectedPoints: 12.6,
      restOfSeasonValue: 76,
      matchupRating: 12,
      opponentWeakness: 48,
      snapShare: 43,
      snapShareTrend: 22,
      carryShare: 38,
      carryShareTrend: 28,
      redZoneUsage: 18,
      expectedFantasyPoints: 13.8,
      injuryAheadOfPlayer: true,
      roleChangeSignal: 72,
      scheduleImprovement: 24,
      projectedRoleDurationWeeks: 6,
      addDropMomentum: 38,
      rosteredPercent: 41,
      injuryStatus: "ACTIVE",
    },
    {
      id: "fa-wr",
      name: "Slot Streamer WR",
      position: "WR",
      projectedPoints: 11.3,
      restOfSeasonValue: 44,
      matchupRating: 26,
      opponentWeakness: 62,
      routeParticipation: 68,
      targetShare: 18,
      targetShareTrend: 8,
      projectedRoleDurationWeeks: 2,
      addDropMomentum: 16,
      rosteredPercent: 22,
      injuryStatus: "ACTIVE",
    },
  ],
  weeklyMatchup: {
    opponentProjectedPoints: 112.4,
    userProjectedPoints: 106.8,
    matchupLeverageByPosition: { RB: 0.72, WR: 0.54 },
  },
  playoffContext: {
    playoffOdds: 0.46,
    mustWinLevel: 0.58,
    weeksUntilPlayoffs: 9,
  },
  dataFreshness: [
    { source: "ESPN free agents", updatedAt: "2026-10-06T14:10:00Z", stale: false },
    { source: "usage signals", updatedAt: "2026-10-06T13:55:00Z", stale: false },
  ],
};

export const waiverSniperExampleOutput = generateWaiverSniper(waiverSniperExampleInput).recommendation;
