window.FANTASY_IQ_CONFIG = {
  siteName: "MyFantasyIQ",
  leagueName: "Public Demo League",
  leagueSubtitle: "ESPN decision engine demo / season 2026",
  defaultLoadout: "",
  customerName: "Demo Manager",
  customerTeamName: "FantasyIQ Demo Squad",
  customerTeamId: "5",
  logoUrl: "./assets/myfantasyiq-wordmark.svg?v=20260522-wordmark-safe-1",
  logoAlt: "MyFantasyIQ league logo",
  draftCardLabel: "Subscription",
  draftCardValue: "$30/year",
  draftCardNote: "Season Pass for up to 3 ESPN leagues",
  paymentLinkUrl: "../setup.html?mode=precheck",
  additionalLeaguePaymentLinkUrl: "https://buy.stripe.com/dRmcN5aAV1GX0Cc7X3efC02",
  includedLeagueLimit: 3,
  additionalLeaguePriceLabel: "$5/year",
  showSubscribeButton: true,
  supportEmail: "support@myfantasyiq.com",
  liveBoardUrl: "/api/live-boards",
  isDemoPreview: true,
  demoLabel: "Demo Mode",
  demoMessage: "Full sample league with roster, waiver, trade, schedule, and draft-prep examples.",
  fieldLeftLabel: "Fantasy",
  fieldRightLabel: "IQ",
  heroTitle: "Your best fantasy move, ranked fast.",
  heroSubtitle:
    "MyFantasyIQ reads league shape, roster leverage, waiver pressure, trade lanes, and schedule edges, then returns a Main Move Brief with confidence, risk, and the next-best option.",
  useEspnLeagueBranding: false,
  leagueSettings: {
    teamCount: 12,
    scoringType: "ppr",
    scoringLabel: "Full PPR",
    lineupSlots: {
      QB: 1,
      RB: 2,
      WR: 2,
      TE: 1,
      FLEX: 1,
      SUPERFLEX: 0,
      DST: 1,
      K: 1,
      BE: 7,
      IR: 1,
    },
    draftRounds: 16,
    playoffTeams: 6,
    source: "MyFantasyIQ default profile",
  },
  loadouts: {
    "demo-manager": {
      customerName: "Demo Manager",
      customerTeamName: "Sample Team",
      customerTeamId: "5",
      isDemoPreview: false,
      showSubscribeButton: false,
      draftCardLabel: "Customer Dashboard",
      draftCardValue: "Active",
      draftCardNote: "Demo Manager / Sample Team",
      demoLabel: "Customer dashboard",
      demoMessage: "Signed-in customer league loaded.",
      leagueSettings: {
        teamCount: 12,
        scoringType: "ppr",
        scoringLabel: "Full PPR",
        lineupSlots: { QB: 1, RB: 2, WR: 2, TE: 1, FLEX: 1, SUPERFLEX: 0, DST: 1, K: 1, BE: 7, IR: 1 },
        draftRounds: 16,
        playoffTeams: 6,
        source: "Customer setup profile",
      },
      heroSubtitle:
        "Demo Manager's Sample Team Main Move Brief for ranked actions, roster exposure, confidence, and risk limits.",
    },
    "sample-owner": {
      customerName: "Demo Owner",
      customerTeamName: "Demo League",
      customerTeamId: "1",
      isDemoPreview: false,
      showSubscribeButton: false,
      draftCardLabel: "Owner Dashboard",
      draftCardValue: "Owner",
      draftCardNote: "Demo Owner / Demo League",
      demoLabel: "Owner dashboard",
      demoMessage: "Signed-in owner league loaded.",
      leagueSettings: {
        teamCount: 12,
        scoringType: "ppr",
        scoringLabel: "Full PPR",
        lineupSlots: { QB: 1, RB: 2, WR: 2, TE: 1, FLEX: 1, SUPERFLEX: 0, DST: 1, K: 1, BE: 7, IR: 1 },
        draftRounds: 16,
        playoffTeams: 6,
        source: "Customer setup profile",
      },
      heroSubtitle:
        "Demo Owner's Demo League Main Move Brief for ranked actions, roster exposure, confidence, and risk limits.",
    },
  },
};
