window.FANTASY_IQ_CONFIG = {
  siteName: "MyFantasyIQ",
  leagueName: "Public Demo League",
  leagueSubtitle: "ESPN public demo / season 2026",
  defaultLoadout: "",
  customerName: "",
  customerTeamName: "",
  customerTeamId: "",
  logoUrl: "./assets/myfantasyiq-wordmark.svg?v=20260522-centered-com-readable",
  logoAlt: "MyFantasyIQ league logo",
  draftCardLabel: "Subscription",
  draftCardValue: "$30 / year",
  draftCardNote: "Season Pass for up to 3 ESPN leagues",
  paymentLinkUrl: "../setup.html?mode=precheck",
  additionalLeaguePaymentLinkUrl: "https://buy.stripe.com/dRmcN5aAV1GX0Cc7X3efC02",
  includedLeagueLimit: 3,
  additionalLeaguePriceLabel: "$5 / year",
  showSubscribeButton: true,
  supportEmail: "support@myfantasyiq.com",
  liveBoardUrl: "/api/live-boards",
  isDemoPreview: true,
  demoLabel: "Demo Mode",
  demoMessage:
    "Sample league only. No customer account is loaded.",
  fieldLeftLabel: "Fantasy",
  fieldRightLabel: "IQ",
  heroTitle: "Draft smarter. Trade cleaner. Win your league.",
  heroSubtitle:
    "Live draft sync, player values, mock tracking, and trade discipline in one command center.",
  useEspnLeagueBranding: false,
  leagueSettings: {
    teamCount: 12,
    scoringType: "ppr",
    scoringLabel: "Full PPR",
    lineupSlots: {
      QB: 1,
      RB: 2,
      WR: 2,
      TE: 1,
      FLEX: 1,
      SUPERFLEX: 0,
      DST: 1,
      K: 1,
      BE: 7,
      IR: 1,
    },
    draftRounds: 16,
    playoffTeams: 6,
    source: "MyFantasyIQ default profile",
  },
  loadouts: {
    katelyn: {
      customerName: "Katelyn Holladay",
      customerTeamName: "KatAttack",
      customerTeamId: "5",
      isDemoPreview: false,
      showSubscribeButton: false,
      draftCardLabel: "Customer Dashboard",
      draftCardValue: "Active",
      draftCardNote: "Katelyn Holladay / KatAttack",
      demoLabel: "Customer dashboard",
      demoMessage: "Signed-in customer league loaded.",
      leagueSettings: {
        teamCount: 12,
        scoringType: "ppr",
        scoringLabel: "Full PPR",
        lineupSlots: { QB: 1, RB: 2, WR: 2, TE: 1, FLEX: 1, SUPERFLEX: 0, DST: 1, K: 1, BE: 7, IR: 1 },
        draftRounds: 16,
        playoffTeams: 6,
        source: "Customer setup profile",
      },
      heroSubtitle:
        "Katelyn's KatAttack command center for live draft sync, player values, mock tracking, and trade discipline.",
    },
    shayne: {
      customerName: "Shayne Holladay",
      customerTeamName: "Gronk if you like TDs",
      customerTeamId: "1",
      isDemoPreview: false,
      showSubscribeButton: false,
      draftCardLabel: "Owner Dashboard",
      draftCardValue: "Owner",
      draftCardNote: "Shayne Holladay / Gronk if you like TDs",
      demoLabel: "Owner dashboard",
      demoMessage: "Signed-in owner league loaded.",
      leagueSettings: {
        teamCount: 12,
        scoringType: "ppr",
        scoringLabel: "Full PPR",
        lineupSlots: { QB: 1, RB: 2, WR: 2, TE: 1, FLEX: 1, SUPERFLEX: 0, DST: 1, K: 1, BE: 7, IR: 1 },
        draftRounds: 16,
        playoffTeams: 6,
        source: "Customer setup profile",
      },
      heroSubtitle:
        "Shayne's Gronk if you like TDs command center for live draft sync, player values, mock tracking, and trade discipline.",
    },
  },
};
